### ISSUE TITLE
Trying to test

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [rsms/immutable-cpp#1]
I am trying to test a persistent graph with Catch, but i can't even create a simple array. What am i doing wrong ? Thx for your help. 

`#define CATCH_CONFIG_MAIN
# include "catch.hpp"
# include "immutable/array.h"

using namespace immutable;

TEST_CASE( "Create array" ) {
    auto a = Array<int>::empty;
}`

Compile command => g++ -I .. -std=c++14 mytest.cc -o test

error =>
Undefined symbols for architecture x86_64:
  "immutable::ArrayImp::EMPTY", referenced from:
    immutable::Array<int>::empty() in Owntest-ac78fd.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1

**Comment by akubera** [comment]
If you're actually doing `auto a = Array::empty;` you're missing the templated type parameter and the parenthesis calling the method: `auto a = Array<int>::empty();`

**Comment by rsms** [comment]
What @akubera is saying. `Array` must be given a value type as it's a template. What's happening here is that because of C++'s flexibility, your `a` symbol is a reference to the type-unbound `Array<T>::empty` function (for use with bind et al.) That's probably why you're not getting a compiler error earlier on, but are getting a linker error.

Two things to notice in the example below:
- Use of type parameter (`int` below; can be any type)
- Empty is a function, not a value (`()` after `empty`)

``` cc
auto a = Array<int>::empty();
auto b = a->push(123);
printf("a size=%u", a.size()); // a size=0 because still the empty array
printf("b size=%u", b.size()); // b size=1 because it had "123" added to it
```

Have a look here for some resources to get you started learning C++: http://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list/388282#388282
